"""Demo routes — powers the public Fundle-branded product demo at /demo.

- POST /api/demo/session : issues a JWT for the read-only demo account (no password
  exposed to the frontend). The account is `brand_admin` + `is_demo=True` so the guided
  tour can VIEW every screen, while every write is blocked by the demo guard in
  `auth.get_current_user` (and Fundle Brain write-tools are blocked for demo users).
- POST /api/demo/tts     : returns audio/mpeg narration generated by OpenAI TTS via the
  Emergent universal key, cached by content hash so each line is only generated once.
"""
import hashlib
import os
import uuid
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel
from dotenv import load_dotenv

from database import users_col, db
from auth import create_token, get_current_user, hash_password

load_dotenv()

router = APIRouter(prefix="/demo", tags=["demo"])

DEMO_EMAIL = "demo@fundle.io"
DEMO_NAME = "Fundle Demo (Read-only)"
DEMO_PASSWORD = "FundleDemo@2026"
DEFAULT_VOICE = "nova"
TTS_MODEL = "tts-1"
MAX_TTS_CHARS = 1200

tts_cache_col = db["tts_cache"]


async def ensure_demo_user() -> dict:
    """Idempotently create / self-heal the read-only demo account.

    Returns a clean dict (no `_id` / `password_hash`).
    """
    user = await users_col.find_one({"email": DEMO_EMAIL}, {"_id": 0, "password_hash": 0})
    if user:
        if (not user.get("is_demo")) or (not user.get("is_active", True)) or user.get("role") != "brand_admin":
            await users_col.update_one(
                {"id": user["id"]},
                {"$set": {"is_demo": True, "is_active": True, "role": "brand_admin"}},
            )
            user = await users_col.find_one({"email": DEMO_EMAIL}, {"_id": 0, "password_hash": 0})
        return user
    doc = {
        "id": uuid.uuid4().hex,
        "email": DEMO_EMAIL,
        "name": DEMO_NAME,
        "role": "brand_admin",
        "is_active": True,
        "is_demo": True,
        "password_hash": hash_password(DEMO_PASSWORD),
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    await users_col.insert_one(doc)
    return {k: v for k, v in doc.items() if k not in ("_id", "password_hash")}


@router.post("/session")
async def demo_session():
    """Public — start a read-only demo session and return a short-lived token."""
    user = await ensure_demo_user()
    token = create_token(user["id"], user["role"], user["email"])
    return {
        "token": token,
        "user": {
            "id": user["id"],
            "email": user["email"],
            "name": user["name"],
            "role": user["role"],
            "is_demo": True,
        },
    }


class TTSRequest(BaseModel):
    text: str
    voice: str | None = None


@router.post("/tts")
async def demo_tts(req: TTSRequest, user: dict = Depends(get_current_user)):
    """Return narration audio (MP3). Cached by hash so each line is generated once."""
    text = (req.text or "").strip()
    if not text:
        raise HTTPException(status_code=400, detail="text is required")
    if len(text) > MAX_TTS_CHARS:
        text = text[:MAX_TTS_CHARS]
    voice = (req.voice or DEFAULT_VOICE).strip() or DEFAULT_VOICE
    key = hashlib.sha256(f"{TTS_MODEL}:{voice}:{text}".encode("utf-8")).hexdigest()

    cached = await tts_cache_col.find_one({"_id": key})
    if cached and cached.get("audio"):
        return Response(
            content=bytes(cached["audio"]),
            media_type="audio/mpeg",
            headers={"Cache-Control": "public, max-age=86400", "X-Cache": "HIT"},
        )

    from emergentintegrations.llm.openai import OpenAITextToSpeech
    tts = OpenAITextToSpeech(api_key=os.getenv("EMERGENT_LLM_KEY"))
    try:
        audio = await tts.generate_speech(text=text, model=TTS_MODEL, voice=voice)
    except Exception as e:  # noqa: BLE001
        raise HTTPException(status_code=502, detail=f"TTS generation failed: {e}")

    await tts_cache_col.update_one(
        {"_id": key},
        {"$set": {
            "audio": audio,
            "voice": voice,
            "model": TTS_MODEL,
            "chars": len(text),
            "created_at": datetime.now(timezone.utc).isoformat(),
        }},
        upsert=True,
    )
    return Response(
        content=audio,
        media_type="audio/mpeg",
        headers={"Cache-Control": "public, max-age=86400", "X-Cache": "MISS"},
    )
